services:
  app:
    build: .
    container_name: csi-m1
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: csi-m1
    ports:
      - "127.0.0.1:6969:5432" # <external>:<internal> port binded to localhost only
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: